services:

  #Postgres para la API OLAP
  postgres_olap:
    image: postgres:15
    container_name: postgres_olap
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aaaa
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_olap_data:/var/lib/postgresql/data

  # Bigdamated + API Carga de datos + MongoDB
  bigdatamed:
    build:
      context: .
      dockerfile: Dockerfile.bigdatamed
    ports:
      - "8000:8000"  # App
      - "5000:5000"  # API de carga
    depends_on:
      - servicios_olap
    volumes:
      - sqlite_data:/bigdatamed/bigdatamed-main/db.sqlite3

  # API de operaciones + PostgreSQL
  servicios_olap:
    build:
      context: .
      dockerfile: Dockerfile.servicios_olap
    depends_on:
      - postgres_olap
    environment:
      POSTGRES_HOST: postgres_olap
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aaaa
      POSTGRES_DB: postgres
    ports:
      - "8001:8001"
volumes:
  postgres_olap_data:
  sqlite_data: